import { Component, OnInit } from '@angular/core';
declare var $;
declare var _;
@Component({
  selector: 'app-speakers-page',
  templateUrl: './speakers-page.component.html',
  styleUrls: ['./speakers-page.component.sass']
})
export class SpeakersPageComponent implements OnInit {
  speakers = [
    { index: 0, image: 'assets/images/Speakers/Arif.jpg', name: 'Arif Khoja', session: 'Using Dialogflow to build actions', sessionDetail: 'Dialogflow (formerly Api.ai, Speaktoit) is a Google-owned developer of human–computer interaction technologies based on natural language conversations. uou need to know 3 core methods i.e. intents, contexts, entities; to learn and Build Actions, Skills, bots, and apps for the Google Assistant, Alexa, Cortana, Facebook Messenger and other platforms ', tag: 'Mobile', work: 'Infosense Global, Gandhinagar', fb: '', git: 'https://github.com/JaldeepAsodariya', link: 'https://www.linkedin.com/in/arif-khoja', bio: 'I am a software engineer. i am a Javascript Enthusiatic who loves logical programming and has first hand experience in building a cutting edge internet product using Angular. I am also an open source freak and keen about learning and sharing. I write Javascript both frontend and backend. I love learning and sharing tech all the time. I also has a hands on experience in SEO, nodejs, dialogflow and write articles about latest emerging technologies.' },    
    { index: 1, image: 'assets/images/Speakers/Bhavik.jpg', name: 'Bhavik Makwana', session: 'Hitchhiker\'s guide to the Flutter', sessionDetail: 'Flutter comes with the reactive framework and use the reactive views, which you can take to the next level by also applying reactive principles to your app’s data model. In this talk I will introduce and give small example that how can you make an app that has more reactive and can be use to update and manage the state in your application.', tag: 'Mobile', work: 'Multidots, Ahmedabad', fb: '', git: 'https://github.com/ibhavikmakwana/', link: 'http://www.linkedin.com/in/ibhavikmakwana', bio: 'I am working as an Android Developer at Multidots Solution Pvt Ltd. An Open source enthusiast, Google Certified Associate Android Developer and Google Scholar for the Android Nanodegree. I am a fanboy of Flutter and ConstraintLayout' },    
    { index: 2, image: 'assets/images/Speakers/Charmi.jpg', name: 'Charmi Choksi', session: 'ML: The Past, Present and Future of AI', sessionDetail: 'It\'s no more a secret that Artificial intelligence (AI) is transforming the way we live and work, like never before, revolutionizing the world around us. Contributing to this larger idea of building an “AI empowered India”, this talk will enable a platform to learn for ML enthusiasts which will cover basics of Machine Learning, the difference between ML, DL, and AI, whether ML is reality or just a hype?, its real-life applications, and frameworks and libraries to be used. Apart from it, the hands-on session/ demo given in the link below can be explained.', tag: 'Web', work: 'Student, Ahmedabad University', fb: '', git: 'https://github.com/charmichokshi/', link: 'https://www.linkedin.com/in/charmichokshi/', bio: 'Working with data and predicting future based on it is Charmi\'s passion and it has always made her feel like a Magician! She is an AI and Data enthusiast who is always willing to learn from new challenges and love to share the experiences with others. She has facilitated the first pilot of Machine Learning Crash Course in India back in September 2017 and was a Research Trainee at Indian Space Research Organisation in summer 2018. Currently, she is a Teaching Assistant and a final year student of ICT Engineering at Ahmedabad University.' },    
    { index: 3, image: 'assets/images/Speakers/Hardy.jpg', name: 'Hardy Patel', session: 'Jetpack Joyride', sessionDetail: 'In google IO \'18 jetpack has been anounced as a bunch of libraries which divides in 4 major aspects.Architectural, behavoural etc. It increases the readability of the code.', tag: 'Mobile', work: 'Volansys Technologies, Ahmedabad', fb: '', git: '', link: 'https://speakerdeck.com/hardy/a-joy-ride-with-jetpack', bio: 'She is an energetic Sr.Engineer at Volansys Technologies who is able to work alongside other talented IT professionals in creating mobile apps of very highest standards.' },    
    { index: 4, image: 'assets/images/Speakers/Jaldeep.jpg', name: 'Jaldeep Asodariya', session: 'Android Things: Things matter', sessionDetail: 'Android Things is an Android-based embedded operating system platform by Google. Android Things lets you build professional, mass-market products on a trusted platform, without previous knowledge of embedded system design. This talk covers 1) How to start with Android Things, Flash OS on development board and Connect devices with NXP Pico i.MX7D board, 2) Control home appliances using Android mobile & Google Assistant application.', tag: 'Mobile', work: 'Jain Bhavesh Solutions, Ahmedabad', fb: '', git: '', link: 'https://twitter.com/JaldeepAsodariy', bio: 'Jaldeep Asodariya is an Android Developer and working at Jain Bhavesh Solutions. As he developed many enormous emerging Android Application so far and got client’s satisfaction through his Development work. He is a core organizing team member of Google Developer Group (GDG), Ahmedabad. Jaldeep is very much interested in IoT (Internet of Things) and Android Things. He has good hands over to develop Google Assistant Applications as well as he has proficient knowledge in NodeJS.' },    
    { index: 5, image: 'assets/images/Speakers/Jinal.jpg', name: 'Jinal Shah', session: 'Angular Web Elements', sessionDetail: 'Angular elements are Angular components packaged as custom elements, a web standard for defining new HTML elements in a framework-agnostic way.', tag: 'Web', work: 'Cofounder, Brainoorja Creations ', fb: '', git: 'https://github.com/jinalshah999', link: 'https://jinalshahblog.wordpress.com/', bio: 'Jinal Shah is the cofounder of Brainoorja Creations (www.brainoorja.com) and a corporate trainer imparting knowledge on various cutting-edge technologies, such as – Node JS, Angular, ionic2, and Bot framework. His IT skills and continuous contribution to developer community has earned him Microsoft MVP (Most Valuable professional) Award. Jinal is having a B.E degree in Computer Science, and is actively associated with academics and training programs for students enrolled in various IT courses in various technical institutions.' },
    { index: 6, image: 'assets/images/Speakers/Naitik.jpg', name: 'Naitik Shah', session: 'Introduction to Scrum', sessionDetail: 'Introduction to Scrum covers what, why and How of the scrum. Starting with traditional development approach, its Pros and Cons and how scrum helps to overcome it. Scrum certification & Road map.', tag: 'Web', work: 'Infosense Global, Gandhinagar', fb: '', git: '', link: 'https://www.linkedin.com/public-profile/settings?trk=d_flagship3_profile_self_view_public_profile', bio: 'I am Certified Scrum Master (CSM) with more than eleven years of experience in the IT industry. I started with agile and Scrum back in 2011, when I was working in Pune with reputed MNC. I believe the worlds of work and life can be balanced and more successful by using SCRUM.' },        
    { index: 7, image: 'assets/images/Speakers/Naresh.jpg', name: 'Naresh Kumar', session: 'Demystifying Front-End Security', sessionDetail: 'Security is big concern in the Web Application. It is must that a back-end developer should do a secure coding to make a web application secure. It is as important for a front-end developer to do developing in a secure manner. In 20% cases , the lack of security in front-end leads to a critical attack on a web application.', tag: 'Web', work: 'Student, GTU', fb: '', git: 'https://github.com/nareshkr22', link: '', bio: 'Being a Information Technology passout student , Naresh have learned and worked on Core PHP and python language. As a Master’s student of Cyber Security in Gujarat Technological Univerisity, he have acquired skills in security analysis of various software and systems..Currently he is pursuing M.E in Cyber Security from GTU and working on security and privacy related issues in various IoT communication protocols. Naresh is a Certified Ethical hacker recognized by EC Council' },
    { index: 8, image: 'assets/images/Speakers/Krunal.jpg', name: 'Krunal Kapadiya', session: 'Jetpack Joyride', sessionDetail: 'In google IO \'18 jetpack has been anounced as a bunch of libraris which divides in 4 major aspects.Architectural, behavoural etc. It increases the readability of the code.', tag: 'Mobile', work: 'Volansys Technologies, Ahmedabad', fb: '', git: '', link: 'https://krunal3kapadiya.app', bio: 'Google certified associate Android developer. Machine learning enthusiastic' },    
    { index: 9, image: 'assets/images/Speakers/Parth.jpg', name: 'Parth Jansari', session: 'Flutter Animations: Motion Awakens', sessionDetail: 'lets learn how to animate things in flutter with a pinch of darkside.', tag: 'Mobile', work: 'Organizer, GDG Gandhinagar', fb: 'https://www.facebook.com/parth.jansari.3', git: 'https://github.com/parth181195', link: '', bio: 'Parth is a guy who is trying to grow up and do mature stuff and work but ends up designing, playing games(most of the time) or watching Movies/Tv Series.Parth has five years of experience in designing and two years experience in front-end development. Parth uses Angular for Creating frontend, ionic and Flutter to create hybrid apps. Parth has mastery over most of the adobe creative suite apps. Currently, Parth is exploring Flutter as he believes it can be a replacement for ionic 2 and all other hybrid app frameworks.' },
    { index: 10, image: 'assets/images/Speakers/manohar.jpeg', name: 'Manohar Allu', session: 'Serverless Computing on GCP', sessionDetail: 'It’s a managed solution by google where you don’t have to deploy your code, it allows you to build and run applications and services without thinking about servers. With serverless computing, your application still runs on servers, but all the server management is done by GCP', tag: 'Web', work: 'Zypher, Gandhinagar', fb: '', git: 'https://github.com/parth181195', link: '', bio: 'Manohar is a pythonist at Day and a Gamer("DOTA 2") at night. Manohar works at Zypher as a junior software engineer which is a Gandhinagar based tech startup. At Zypher he contributes in building really cool and amazing stuff. He has completed his Diploma in Computer Engineering from Government Polytechnic, Gandhinagar. Apart from Academics and work, he is a dog lover, a tech enthusiast, an avid reader("Quora") and a lover of Sophia.' },
    { index: 11, image: 'assets/images/Speakers/chintan.jpg', name: 'Chintan Soni', session: 'Stabbing the Dagger in Kotlin made easy', sessionDetail: 'Dagger is still one unsolved mystery to average number of Android Developers. This talk will take participants to 10 minutes roller coaster ride around the world of Dagger, and it will help them learn to use it with Kotlin.', tag: 'Mobile', work: 'Simform Solutions , Ahmedabad', fb: 'https://www.facebook.com/chintansoni202', git: 'https://github.com/chintansoni202', link: '', bio: 'Chintan Soni, a passionate Sr. Software Engineer at Simform Solutions Pvt. Ltd., a workplace that adopted Kotlin from the day of announcement as first class support for Android Development. He has been exploring and strengthening his roots in Android Development for more than 5 years. Not only in Android, but also he has experience on various cross platform frameworks and tools, Back-end and Web technologies as well. He frequently contributes to his native communities in Gujarat by delivering technical sessions at GDG Ahmedabad, Gandhinagar, Baroda and DAIICT. He spends his leisure in creating examples to help developer community at Github and Stackoverflow. And when he is bored out of work and chooses to game, he becomes deadly sniper in PUBG.' },
    // { index: 9, image: 'assets/images/Speakers/Parth.jpg', name: 'Parth Jansari', session: 'Flutter Animations: Motion Awakens', sessionDetail: 'lets learn how to animate things in flutter with a pinch of darkside.', tag: 'Mobile', work: 'Organizer, GDG Gandhinagar', fb: 'https://www.facebook.com/parth.jansari.3', git: 'https://github.com/parth181195', link: '', bio: 'Parth is a guy who is trying to grow up and do mature stuff and work but ends up designing, playing games(most of the time) or watching Movies/Tv Series.Parth has five years of experience in designing and two years experience in front-end development. Parth uses Angular for Creating frontend, ionic and Flutter to create hybrid apps. Parth has mastery over most of the adobe creative suite apps. Currently, Parth is exploring Flutter as he believes it can be a replacement for ionic 2 and all other hybrid app frameworks.' },
  ]
  activeFilters = [];
  availableFilters = [];
  constructor() { }

  ngOnInit() {
    for (let i in this.speakers) {
      this.availableFilters.push(this.speakers[i].tag)
    }
    this.availableFilters = _.uniq(this.availableFilters)
    setTimeout(() => {
      $('.modal').modal();
    }, 500)
  }

  setFilters(name) {
    if (this.activeFilters.indexOf(name) !== -1) {
      this.activeFilters.splice(this.activeFilters.indexOf(name), 1)
    } else {
      this.activeFilters.push(name)
    }
  }
  filter(tag) {
    if (this.activeFilters.length !== 0) {
      return this.activeFilters.indexOf(tag) !== -1 ? true : false;
    } else {
      return true;
    }
  }
}
