language: node_js
node_js:
  - "9"
dist: trusty
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

install:
  - npm install 

script:
  # - yarn lint
  - ng build --base-href https://gdg-gandhinagar.github.io/devfest-18/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/devfestSite
  keep-history: true
  on:
    branch: master